### ISSUE TITLE
Hebrew Nikkud are placed wrong on a ש

### ISSUE THREAD

**Issue by bjesus** [alefalefalef/Varela-Round-Hebrew#7]
Hi, thanks for the great font.

When taking the word שָׁלוֹם for example, the dot should be placed one right side above the letter ש, indicating it's a "Shin", not a "Sin". However, if you copy and paste this word to the example page on https://fonts.google.com/specimen/Varela+Round , you'd see the dot appears on the wrong side (on the left side), making the word Shalom pronounced like Salom.

We were using this font for some educational project for kids, and we literally had to switch because kids got confused...

**Comment by avrahamcornfeld** [comment]
Fixed

**Comment by bjesus** [comment]
Awesome! thank you 🎉
